package com.myspace.helloworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Grant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String initiative;

	public Grant() {
	}

	public java.lang.String getInitiative() {
		return this.initiative;
	}

	public void setInitiative(java.lang.String initiative) {
		this.initiative = initiative;
	}

	public Grant(java.lang.String initiative) {
		this.initiative = initiative;
	}

}