package com.myspace.helloworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class junk implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private java.lang.String phone;

	public junk() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public junk(java.lang.String name, java.lang.String phone) {
		this.name = name;
		this.phone = phone;
	}

}