package com.myspace.helloworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class junk implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private java.lang.String phone;

	private java.lang.String address1;

	private java.lang.String city;

	private java.lang.String state;

	private java.lang.String zip;

	public junk() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getAddress1() {
		return this.address1;
	}

	public void setAddress1(java.lang.String address1) {
		this.address1 = address1;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getZip() {
		return this.zip;
	}

	public void setZip(java.lang.String zip) {
		this.zip = zip;
	}

	public junk(java.lang.String name, java.lang.String phone,
			java.lang.String address1, java.lang.String city,
			java.lang.String state, java.lang.String zip) {
		this.name = name;
		this.phone = phone;
		this.address1 = address1;
		this.city = city;
		this.state = state;
		this.zip = zip;
	}

}