package com.myspace.helloworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable {

	static final long serialVersionUID = 1L;

    private int status;
    
	private java.lang.String message;
	public static final int HELLO = 0;
	public static final int GOODBYE = 1;

	public Message() {
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public Message(java.lang.String message) {
		this.message = message;
	}
	
	public int getStatus(){
	    return this.status;
	}
	public void setStatus(){
	    this.status = status;
	}

}