package com.myspace.helloworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class tag implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public tag() {
    }




}