package com.myspace.helloworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class tag implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String category;
	private java.lang.String subCategory;

	public tag() {
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public java.lang.String getSubCategory() {
		return this.subCategory;
	}

	public void setSubCategory(java.lang.String subCategory) {
		this.subCategory = subCategory;
	}

	public tag(java.lang.String category, java.lang.String subCategory) {
		this.category = category;
		this.subCategory = subCategory;
	}

}